#!/bin/bash

echo -ne '[#####                  ]   (25%)\r'
sleep 1
echo -ne '[############           ]   (50%)\r'
sleep 1
echo -ne '[################       ]   (75%)\r'
sleep 1
echo -ne '[#######################]   (100%)\r'
echo -ne '\n'
